[package]
name = "allfeat-faucet-shared"
version = "0.1.0"
edition = "2021"
authors = ["Allfeat labs. <hello@allfeat.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
